rht-labs/tech-exercise

docs/2-attack-of-the-pipelines/3-the-pipelines.md

Typo fix for 3-the-pipelines.md

---

docs/3-revenge-of-the-automated-testing/1a-jenkins.md
docs/3-revenge-of-the-automated-testing/1b-tekton.md

This PR includes a set of small changes from the review of the #6

Reviewing [exercise] - Sonar Scanning

---

docs/3-revenge-of-the-automated-testing/1-sonar-scanning.md

This should reduce steps a little bit.

Use pull --rebase

---

docs/3-revenge-of-the-automated-testing/4b-tekton.md

The example prompts the student to edit a file, which is shown in screenshots, but doesn't indicate which file it is. If you're familiar with Java it's pretty easy to find, but maybe some will find that confusing.

Add file to match screenshot

---

docs/5-the-deployments-strike-back/2-blue-green-deployments.md

This needs to append, not replace

Fix redirection

---

docs/1-the-manual-menace/README.md

Someone once told me to never use the word "utilize" because it just means "use" and adds no extra value. So let's just use "use" instead 😜

Grammar tweak  🤖

---

docs/4-return-of-the-monitoring/1-enable-monitoring.md

Screenshots probably also need adjusting

Adjust to "monitoring" -> "observe" UI rename

---

docs/2-attack-of-the-pipelines/2-app-of-apps.md

Pet battle deployment definition in the summary did not match with the previous code section, so the student could be missed about the right content to copy and review.

:bug: FIX - Pet battle deployment definition

---

docs/1-the-manual-menace/1-the-basics.md

Hey, just started fixing up "The Basics" to use the new `zsh` default and started hacking away at some grammar.
Just now noticing https://github.com/rht-labs/tech-exercise/pull/88 has some of the same so will need to sync these up with the @eranderson921 edits. 🔄

Updating exercise 1-the-basic.md for zsh default plus grammar

---

docs/slides/content/kick-off.md

Edit completed. 
There is a minor issue with the graphic "Target Outcomes - World Health Organization"
In the top bubbles, the "descenders", or parts of the letter that drop below the line (e.g. "p"), are cut off.

GLS edit of Kick-off completed

---

docs/slides/content/automated-testing.md

1. Please note: There are two comments that need review and the content fixed. 
The second one, under "The Game Begins Again" especially needs attention as it is not grammatically correct. I've made a suggestion with my comment in the file.
2. I would also suggest modifying the intro to the slide with the following graphic:
```
```
The intro has a punctuation error, a subject-verb agreement error ("the intersection ..provides),  and confuses the words "that" and "which".
Suggested edit:
"The intersection of TDD, DDD, and BDD provides a hybrid approach to development that assures predictable and productive outcomes."

GLS edit of automated testing completed

---

docs/slides/content/social-contracts.md

GLS edit of Social Contracts completed.

---

docs/slides/content/non-functional-map.md

Line 83  was "Let's not think of all the _other_ things they need to do to harder their application."

Typo fix non-functional-map.md slides

---

docs/slides/content/metrics-based-process-mapping.md

There is a spelling mistake in one of the graphics:
In this graphic, the word "Chose" should be "Choose"
"Choose the longest...." - "chose" is the past tense of "choose."

GLS edt MBPM completed.

---

docs/1-the-manual-menace/1-the-basics.md

Grammar tweak to 1-the-basics.md

---

docs/slides/content/metrics-based-process-mapping.md

Remove dupe VSM from MBPM related practices slide

---

docs/slides/content/pair-and-mob-programming.md

remote friendly tweak

---

docs/1-the-manual-menace/1-the-basics.md

Add change uname/pass tip to step8 in the basics

---

docs/1-the-manual-menace/1-the-basics.md
docs/1-the-manual-menace/2-argocd.md
docs/slides/content/tech-exercise-i.md

Tip to reassure students the copy paste did work and will run as designed.

Agro cd new tip

---

docs/1-the-manual-menace/1-the-basics.md
docs/1-the-manual-menace/2-argocd.md
docs/slides/content/tech-exercise-i.md

Many people may not understand what 'watch' mode means or that you need to do something to continue to the next step. Updated instructions to better clarify how the student must do the control-c in order to break the watch and continue to the next step.

Exercise1 step4 update

---

docs/3-revenge-of-the-automated-testing/1-sonar-scanning.md

Just fixing a small typo in the doc.
Thanks for the great lab.

🕵 Fix small documentation typo 🕵

---

docs/3-revenge-of-the-automated-testing/2b-tekton.md

While doing the exercice we noticed a missing " at the end of the md example

correct missing "

---

docs/slides/content/tech-exercise-iii.md

Technical Exercise III doesn't include references about some of the practices covered. This PR includes a set of references related with test automation and priorization.

🌱 Added OPL references in Tech Exercise III

---

docs/slides/content/tech-exercise-i.md
docs/slides/content/tech-exercise-ii.md
docs/slides/content/tech-exercise-iii.md
docs/slides/content/tech-exercise-iv.md
docs/slides/content/tech-exercise-v.md

:rotating_light: This is an experiment and is open to discussion, and revision before merging it.
After a set of runs, we found that in many cases the attendees don't follow up on the big picture at the beginning of the activity, as many of the concepts, or tools are described later.
@earvonen proposed a new idea to move the outcomes and big picture after the practices of the technical exercise and before the exercise instructions. It was very well from there and we applied it in the rest of the technical exercises.
The attendees gave us good feedback about this new approach and we could explain better the components and their functions in the big picture.
We are glad to get other opinions, comments, and ideas about this experiment.

🧐 [Experiment][WIP] Moving Outcomes and Big Picture before tech instructions

---

docs/2-attack-of-the-pipelines/3b-tekton.md
docs/slides/content/non-functional-map.md
docs/slides/content/tech-exercise-iii.md

Removed the tekton thingy as it always ran into issues for people the way it rendered....

🐨 FIX - minor changes from last runs in LDN 🐨

---

docs/3-revenge-of-the-automated-testing/4b-tekton.md

@pabrahamsson one from your team

🐠 FIX - broken stuff on linting  🐠

---

docs/slides/content/metrics-based-process-mapping.md

swapped "changes" and "failures" wording to be more accurate and correct.

fixed wording on metrics of velocity

---

.github/workflows/docs-release-and-build-image.yaml

Add an GH action to build and publish TL500 Tech Exercise image on Release

GitHub action to build and push TL500 image

---

docs/1-the-manual-menace/1-the-basics.md
docs/config/all.json
docs/index.html

@oybed  / @jfilipcz  / @jtudelag  - I just threw this together quickly if it's any use for yous to test out and if it helps with the variable stuff for GLS
FYI @eformat / @ckavili

🐁 ADD - hook to configure the location of CRW Devfile 🐁

---

.github/workflows/tl500-tech-exercise-test-build-push.yaml

Fix workflow path

---

docs/1-the-manual-menace/2-argocd.md

So we can easily SSL-verify-ignore them:)

Add an explicit repositories definitions in ArgoCD CR

---

docs/2-attack-of-the-pipelines/1-sealed-secrets.md

@ckavili another quick one for you please ![bitmoji](https://sdk.bitmoji.com/render/panel/b182cbdd-69b0-445d-86d3-e2bab7f33cd1-5861b8d6-6071-4533-939a-16117539af15-v1.png?transparent=1&palette=1&width=246)

🦟 FIX - username for teamname 🦟

---

docs/1-the-manual-menace/1-the-basics.md
docs/3-revenge-of-the-automated-testing/1a-jenkins.md
docs/3-revenge-of-the-automated-testing/4b-tekton.md
docs/config/all.json
docs/index.html

Revert of https://github.com/rht-labs/tech-exercise/pull/232 for the case there's no real choice for OCP 4.11

Revert of OCP 4.11 content on a temporary branch

---

docs/5-the-deployments-strike-back/1-autoscaling.md

This PR replaces the `hey` load testing tool with `k6`, along with necessary configuration steps.

Replace hey with k6 for running load tests

---

docs/slides/content/impact-mapping.md

Small PR to link the Impact Mapping OPL practice in its slides.
(No so much effort here).

🏷️ Add Impact mapping reference

---

docs/slides/content/automated-testing.md
docs/slides/content/kick-off.md

Link to the new practices published :receipt: (BDD, Ice Breakers) in OPL site in the main decks.

🔍 Link to OPL practices

---

docs/1-the-manual-menace/1-the-basics.md
docs/2-attack-of-the-pipelines/3c-create-new-group.md
docs/slides/content/tech-exercise-i.md

you were too quick @eformat haha last one, promise!

🐬 s/crw/devspaces/g 🐬

---

docs/slides/content/priority-sliders.md

Fix Link to priority sliders

---

docs/slides/content/tech-exercise-i.md

Fixed link to the related practice

Update link to everything as code

---

docs/slides/content/retrospectives.md

Update retrospective links

---

README.md

But first you have to become one 🤓

I just became a contributor

---

docs/99-the-rise-of-the-cluster/1-tooling-installation.md

just a minor update after moving the helm chart from dc to deployment ✨

✨minor update on the doc✨

---

docs/4-return-of-the-monitoring/2-create-alerts.md
docs/4-return-of-the-monitoring/3-logging.md

I would also like to update the instructions with Loki and Vector stuff if @eformat gives me a hand to update the RHPD setup with the latest OpenShift 🙈

🐈 add some descriptions🐈

---

docs/1-the-manual-menace/1-the-basics.md
docs/1-the-manual-menace/2-argocd.md
docs/1-the-manual-menace/3-ubiquitous-journey.md
docs/1-the-manual-menace/4-extend-uj.md
docs/1-the-manual-menace/666-here-be-dragons.md
docs/1-the-manual-menace/README.md
docs/2-attack-of-the-pipelines/1-sealed-secrets.md
docs/2-attack-of-the-pipelines/2-app-of-apps.md
docs/2-attack-of-the-pipelines/3-the-pipelines.md
docs/2-attack-of-the-pipelines/3a-jenkins.md
docs/2-attack-of-the-pipelines/3b-tekton.md
docs/2-attack-of-the-pipelines/666-here-be-dragons.md
docs/2-attack-of-the-pipelines/README.md
docs/3-revenge-of-the-automated-testing/README.md
docs/README.md

This PR includes some minor suggestions to improve wording.

Minor fixes, re-wording

---

docs/99-the-rise-of-the-cluster/1-tooling-installation.md

This PR fixes a typo on the base64 decoding of the IPA admin password and allows to run the script to create the student group and users non interactively to facilitate automation.

⚡️ Enable non-interactive creation of group/users ⚡️

---

docs/1-the-manual-menace/4-extend-uj.md

Update nexus chart version

---

tekton/templates/pipelines/maven-pipeline.yaml

closes https://github.com/rht-labs/tech-exercise/issues/302

⛵️ ClusterTask is replaced with resolver ⛵️

---

docs/2-attack-of-the-pipelines/2-app-of-apps.md
docs/2-attack-of-the-pipelines/3b-tekton.md
docs/5-the-deployments-strike-back/1-autoscaling.md

[🙌🏻 Application of Applications](https://rht-labs.com/tech-exercise/#/2-attack-of-the-pipelines/2-app-of-apps)
Updated Pet Battle Chart version

Updated Pet Battle Chart version

---

docs/3-revenge-of-the-automated-testing/8b-tekton.md

[🐈 Tekton](https://rht-labs.com/tech-exercise/#/3-revenge-of-the-automated-testing/8b-tekton)
Fix cosign pipeline errors

Added cosign client new version

---

docs/3-revenge-of-the-automated-testing/11-system-test.md
docs/3-revenge-of-the-automated-testing/11a-jenkins.md
docs/3-revenge-of-the-automated-testing/11b-tekton.md
docs/_sidebar.md
tekton/templates/pipelines/maven-pipeline.yaml

[🦤 System Tests](https://rht-labs.com/tech-exercise/#/3-revenge-of-the-automated-testing/11-system-test)
New featyre - Added system testing for Tekton

Added system testing for Tekton

---

docs/1-the-manual-menace/1-the-basics.md
docs/1-the-manual-menace/2-argocd.md
docs/1-the-manual-menace/3-ubiquitous-journey.md
docs/1-the-manual-menace/4-extend-uj.md
docs/1-the-manual-menace/5-this-is-gitops.md
docs/1-the-manual-menace/666-here-be-dragons.md
docs/1-the-manual-menace/README.md
docs/2-attack-of-the-pipelines/1-sealed-secrets.md
docs/2-attack-of-the-pipelines/2-app-of-apps.md
docs/2-attack-of-the-pipelines/3-the-pipelines.md
docs/2-attack-of-the-pipelines/3a-jenkins.md
docs/2-attack-of-the-pipelines/3b-tekton.md
docs/2-attack-of-the-pipelines/3c-create-new-group.md
docs/2-attack-of-the-pipelines/666-here-be-dragons.md
docs/README.md

🐛 Typos fixed on The Manual Menace

---

ubiquitous-journey/values-tooling.yaml

Add comment for StackRox to match the other tools

📝 Add comment for StackRox
