rht-labs/tech-exercise

.github/ISSUE_TEMPLATE/new-slides-content-template.md

GitHub Issue template for Slides Content
It could help to create new issues related with the content of the slides, and practices.
For example: to create issues related with some of the practices in content loop without content created.

:sparkles: Adding Slides Content GH issue template

---

docs/4-return-of-the-monitoring/1-enable-monitoring.md

This PR includes some changes after the review the exercise #14 User Workload Monitoring:
- Enable ServiceMonitor in `tech-exercise` repo instead of the `values.yaml` of `pet-battle` repo
This is because the application is deployed for each environment from that repo and any configuration should be applied in the `values` section of each folder environment. Otherwise are you changing the default values of the pet-battle chart instead of the deployment for each environment.
- Minor typos

Reviewing [exercise] - User workload monitoring

---

docs/2-attack-of-the-pipelines/1-sealed-secrets.md

There is no "configure" button on the Jenkins home page that I can see, but "Manage Jenkins" is clearly visible.
and

Fix UI item needed to access Jenkins credentials

---

docs/2-attack-of-the-pipelines/3a-jenkins.md

This is not interpreted by echo, so it prints out something odd.
This could have been originally a `printf`, maybe?

Remove extraneous \n in echo

---

docs/README.md

The instructions were different to the example which was a bit confusing, so making it consistent in order to avoid common typo errors.

Removes ⚡ escaping slashes⚡ from conventions cos they're not needed 

---

docs/4-return-of-the-monitoring/3-logging.md

It is not very visible that you are in a subshell (the version of bash changes, but the prompt is *very* similar), so people might be confused if they don't remember to exit.

Add instructions to exit rsh

---

docs/slides/content/what-is-devops.md

Typo in link to DevOps Handbook in "What is DevOps?" content slides.

:bug: Fixing DevOps Handbook image link

---

docs/README.md

Reverts rht-labs/tech-exercise#80 because otherwise we need to replace biscuits with kattekrab, or kattekrab with biscuits. And no-one wants that. Really.

Revert "Removes ⚡ escaping slashes⚡ from conventions cos they're not needed "

---

docs/slides/content/tech-exercise-iii.md

In an attempt to fix the ugly line break, let's see if moving the image above the line of text does the trick.

Move image above text to avoid line break

---

docs/1-the-manual-menace/1-the-basics.md
docs/slides/content/tech-exercise-i.md

There is a note about running the Pairing and Mobbing activity if not already done. This is a facilitator note and doesn't need to be in slide ware. The CRW screenshot is in the instructions site and not needed in the slide ware. Once students are logged in, they should follow instructions that are on the exercise instruction site.

Remove Facilitator note and removed a screenshot

---

README.md

The word `test` is rendered in blue in bash syntax blocks, this change removes the syntax highlighting.

Fix small formatting

---

docs/3-revenge-of-the-automated-testing/6a-jenkins.md
docs/3-revenge-of-the-automated-testing/9a-jenkins.md

Some git push commands could fail because there are changes in git remote repo (changes created by the pipelines). The user could be confused, so this PR includes a set of extra warn boxes to help in these cases.

Adding warn boxes regarding git commands

---

docs/2-attack-of-the-pipelines/3a-jenkins.md

Docs mentined create repo, but it confuses user,
because GitLab terminology uses Project.

pipelines-jenkins docs fix repo to gitlab project

---

docs/2-attack-of-the-pipelines/3b-tekton.md

Docs mentioned create `repo`, but it confuses user,
because GitLab terminology uses `Project`.

pipelines-tekton docs fix terminology from repo to gitlab project

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

As we are looking for new contributors, and improve the content (slides, and exercises), we should provide some guidelines for the new contributors.
This PR include an initial version of the standard files in GitHub about:
* Contribution Guide (aka CONTRIBUTING.md file)
* Code of Conduct (aka CODE_OF_CONDUCT.md file)
Maybe this PR could be extended with some tips, comments about best practices or patterns followed in the repo, such as:
* Commit messages
* Emoji use cases

Adding Contribution guides to extend the community

---

docs/1-the-manual-menace/1-the-basics.md
docs/index.html
docs/vars/tl500-variables.json

First out is the `devfile_location`, which allows for the URL to the CRW devfile to be configured at deployment time.

Adding support for using a variables file to configure runtime values

---

docs/1-the-manual-menace/1-the-basics.md
docs/index.html
docs/vars/tl500-variables.json

Reverts rht-labs/tech-exercise#203 as it breaks the `bash` variables in the instructions.

Revert "Adding support for using a variables file to configure runtime values"

---

tests/README.md
tests/container/Containerfile
tests/container/run.sh
tests/regression.sh

Basically this PR makes two things:
* Make curl commands insecure, based on the same reasoning of this other PR: https://github.com/rht-labs/enablement-framework/pull/138 (Basically it is the interim solution for GLS envs untille we find a better approach)
* Be able to run the tests agains an specific repository and branch. Current default repo and and branch remain untouched, unless the env vars `REPO` and `BRANCH` are set.

Make tests environment agnostic

---

docs/2-attack-of-the-pipelines/3a-jenkins.md
tests/doc-regression-test-files/3a-jenkins-Jenkinsfile.groovy

Change following : https://github.com/rht-labs/pet-battle/pull/4

Replace git-plugin with shell git to ensure SSL settings are respected

---

docs/3-revenge-of-the-automated-testing/4a-jenkins.md

As you can see in https://rht-labs.com/tech-exercise/#/3-revenge-of-the-automated-testing/4a-jenkins step 5) the bash code block is not rendered correctly because it has not the bash md tag. This fix adds that tag for getting a correct render.

Add bash code md tag on 4a-jenkins.md

---

docs/4-return-of-the-monitoring/2-create-alerts.md

The docs/4-return-of-the-monitoring/2-create-alerts.md step 5) lab is not working because the pet-battle-api version bump is not done correctly. The instructions teach the student to bump to version 1.3.1, but this is the current version of the pet-battle-api chart at that point (the previous docs/3-revenge-of-the-automated-testing/5b-tekton.md lab bumps to that version, 1.3.1). 
Because of this incorrect version bump, the PrometheusRule object in ArgoCD is not updated with the new alerts rules used on the lab as PetBattleMongoDBDiskUsage, the lab alert is not triggered and the lab fails.
The solution proposed in this PR is to perform a correct pet-battle-api chart version bump to `1.3.2` . I have tested in my GLS TL500 lab that this solution fixes the problem.  Many thanks in advance for …

Fix pet-battle-api version bump on 2-create-alerts.md

---

docs/5-the-deployments-strike-back/1-autoscaling.md

This lecture change instructs the student to use the `k6` tool for load testing the pet-battle app on 1-autoscaling.md. `k6`supports the use of `--insecure-skip-tls-verify` during the load test https requests as required for the GLS TL500 lab env. Please @jfilipcz @eformat  when you can review it. Thanks!

Create k6 lecture for running load tests

---

docs/3-revenge-of-the-automated-testing/8-image-signing.md
docs/3-revenge-of-the-automated-testing/8b-tekton.md

A bugfix for: https://github.com/rht-labs/tech-exercise/issues/242
* Remove --allow-insecure-registry flag for `cosign generate` subcommond since it's not supported in that usecase
* Bump version of cosign set for Tekton pipeline

Update cosign handling

---

docs/2-attack-of-the-pipelines/3b-tekton.md

correct the text saying "Select `pet-battle` " to "Select `pet-battle-api` " .  Actually, the screenshot below is correct and shows/marks the correct folder.

correct the text to match the screenshot

---

docs/slides/content/kanban.md
docs/slides/content/kick-off.md
docs/slides/content/scrum.md
docs/slides/content/social-contracts.md

Update content of different decks to link with the new/old practices in the Open Practice Library:
- Team Identity
- Scrum
- Visualization of Work
No practices without a link in the last slide of each deck :smile:

🌱 Link to OPL practices

---

docs/1-the-manual-menace/4-extend-uj.md
docs/3-revenge-of-the-automated-testing/1-sonar-scanning.md
docs/3-revenge-of-the-automated-testing/2b-tekton.md
docs/3-revenge-of-the-automated-testing/5b-tekton.md
docs/3-revenge-of-the-automated-testing/7b-tekton.md
docs/3-revenge-of-the-automated-testing/8a-jenkins.md
docs/3-revenge-of-the-automated-testing/8b-tekton.md
docs/3-revenge-of-the-automated-testing/9b-tekton.md
docs/4-return-of-the-monitoring/2-create-alerts.md
docs/5-the-deployments-strike-back/1-autoscaling.md
tekton/templates/tasks/bake-image.yaml
tekton/templates/tasks/verify.yaml
tests/doc-regression-test-files/good-4-extend-uj.json
ubiquitous-journey/values-tooling.yaml

- updates charts to latest tool versions
- runs on v4.12 OpenShift now as well
I have done a full run through OK from start to finish for TL500 OK. 
Links with this PR:
https://github.com/rht-labs/enablement-framework/pull/163

🦆 update chart + image versions. adds OCP4.12 support 🦆

---

docs/config/all.json

Che-Theia is removed as a supported IDE (see https://issues.redhat.com/browse/CRW-3663)  So the current OCP 4.11+ workspace link gets 404 error. We need to switch VS Code but that requires changing the screenshots to open terminal etc as well. Therefore I marked the PR as WIP for now. My question @eformat is, should we go only for 4.11+ in the docs in main? I think that'd be better as we have now have tags.

WIP: 🐂 che-theia is removed as supported IDE 🐂

---

ubiquitous-journey/values-tooling.yaml

@tdbeattie is doing a run of the course using upstream this week. They're using a 4.12 cluster so this will need to be changed for the jenkins exercise to work  as per fixes in here 
https://github.com/rht-labs/s2i-config-jenkins/pull/47

🦙 FIX - version of the ocp base for demo system 🦙

---

tekton/templates/tasks/deploy.yaml

This PR fixes the #278 issue.
I would like a double check from my colleages @ckavili @eformat and @springdo .
Maybe the cause is related to the `git config --global --add safe.directory /workspace/output` command executed by the `git-clone` cluster task. I can't remember that command in previous versions or executions of this pipeline.
Ideas? Comments?

:bug: Fix detected dubious ownership in git repo

---

docs/3-revenge-of-the-automated-testing/README.md

Fix broken link to create a second group. The original link produces a 404 error.

:seedling: Fix broken link

---

tekton/templates/tasks/verify.yaml

The current implementation of the Tekton Task verify-deployment fails to commit the rollback changes. Following issues are fixed:
- change image to correctly retrieve git credentials
- fix wrong URL for the git repo
- address detected dubious ownership in repository

🐛 Fix Tekton Task verify-deployment 🐛

---

ubiquitous-journey/values-tooling.yaml

This runs Jenkins as a Deployment instead of deprecated DeploymentConfig
Ref: https://github.com/redhat-cop/helm-charts/pull/613

Bump Jenkins helm chart

---

docs/2-attack-of-the-pipelines/2-app-of-apps.md

Updated Pet Battle API Chart version to deploy the latest version of MongoDB and being able to start the petbattle-api pod correctly.

Updated Pet Battle API Chart version

---

docs/3-revenge-of-the-automated-testing/9b-tekton.md

[🐈 Tekton](https://rht-labs.com/tech-exercise/#/3-revenge-of-the-automated-testing/9b-tekton)
- Solving bugs using an new version of cosign CLI
- Solving bugs skipping server TLS cert verification for syft and cosign CLIs

Solving bugs - Generating and Attesting SBOM

---

docs/1-the-manual-menace/1-the-basics.md
docs/1-the-manual-menace/2-argocd.md
docs/1-the-manual-menace/3-ubiquitous-journey.md

This PR improves the usage of the definition of the repositories from the `ArgoCD` chapter to the `UJ` one. Deploying ArgoCD in the first exercise does not require to declare any reference to the `tech-exercises` repository, as it is not already created. The current definition of the ArgoCD operator[1], the creation of repositories only works the first execution, after that it is required to use the Argo CD Web UI or CLI.
As the `tech-exercise` is created in the next exercise, the documentation is extended to declare the definition of the required secrets (not as GitOps yet) to allow pull changes from it. It is easy create one using the `argocd.argoproj.io/secret-type: repository` label.
This PR simplify the deployment of ArgoCD in the first step, and define the usage of the repositories …

Declare repository definition as secrets
